"""init_library_schema

Revision ID: 69177f9cd004
Revises: c58af97cb89b
Create Date: 2026-09-22 22:17:59.713555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = '69177f9cd004'
down_revision: Union[str, Sequence[str], None] = 'c58af97cb89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('family_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('stockTot', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('editor', sa.String(length=100), nullable=True),
    sa.Column('id_author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_author'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_table('rent_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('dateBeginRen', sa.DateTime(), nullable=False),
    sa.Column('dateEnd', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rent_books_id'), 'rent_books', ['id'], unique=False)
    op.drop_table('items')
    op.drop_index(op.f('idx_users_name'), table_name='users')
    op.drop_index(op.f('sys_c008656'), table_name='users')
    op.drop_table('users')
    op.add_column('app_users', sa.Column('surname', sa.String(length=50), nullable=False))
    op.add_column('app_users', sa.Column('family_name', sa.String(length=50), nullable=False))
    op.add_column('app_users', sa.Column('email', sa.String(length=150), nullable=False))
    op.add_column('app_users', sa.Column('blacklist', sa.Boolean(), nullable=False))
    op.drop_index(op.f('sys_c008667'), table_name='app_users')
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True)
    op.create_index(op.f('ix_app_users_id'), 'app_users', ['id'], unique=False)
    op.drop_column('app_users', 'username')

    # --- AJOUT MANUEL ---

    # Nettoyage et création des rôles Oracle
    op.execute("""
            BEGIN
               EXECUTE IMMEDIATE 'DROP ROLE app_user';
            EXCEPTION WHEN OTHERS THEN NULL;
            END;
        """)
    op.execute("""
            BEGIN
               EXECUTE IMMEDIATE 'DROP ROLE app_admin';
            EXCEPTION WHEN OTHERS THEN NULL;
            END;
        """)

    op.execute("CREATE ROLE app_user")
    op.execute("CREATE ROLE app_admin")

    # Attribution des droits sur les nouvelles tables
    op.execute("GRANT SELECT ON books TO app_user")
    op.execute("GRANT SELECT ON authors TO app_user")
    op.execute("GRANT SELECT, INSERT, UPDATE ON rent_books TO app_user")
    op.execute("GRANT SELECT ON rent_books_id_seq TO app_user")

    # Droits APP_ADMIN
    for table in ["books", "authors", "app_users", "rent_books"]:
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO app_admin")
    for seq in ["books_id_seq", "authors_id_seq", "app_users_id_seq", "rent_books_id_seq"]:
        op.execute(f"GRANT SELECT ON {seq} TO app_admin")

    # Création des utilisateurs Oracle
    op.execute("""
            BEGIN
               EXECUTE IMMEDIATE 'DROP USER alice CASCADE';
            EXCEPTION WHEN OTHERS THEN NULL;
            END;
        """)
    op.execute("""
            BEGIN
               EXECUTE IMMEDIATE 'DROP USER bob CASCADE';
            EXCEPTION WHEN OTHERS THEN NULL;
            END;
        """)

    op.execute('CREATE USER alice IDENTIFIED BY "SecretAlice2026"')
    op.execute('GRANT CREATE SESSION TO alice')
    op.execute('GRANT app_admin TO alice')

    op.execute('CREATE USER bob IDENTIFIED BY "SecretBob2026"')
    op.execute('GRANT CREATE SESSION TO bob')
    op.execute('GRANT app_user TO bob')

    # Insertion des utilisateurs dans la table de l'application (Le hash correspond au mot de passe : 'secret')
    op.execute("""
            INSERT INTO app_users (id, surname, family_name, email, password, blacklist) 
            VALUES (app_users_id_seq.NEXTVAL, 'Alice', 'Admin', 'alice@admin.com', '$argon2id$v=19$m=65536,t=3,p=4$RNR/ZzUZ4S4a+DrTWzHoFw$QV6K0vFNr/f89mwdTxCCezLISmkYl+Y+7Z/yARL87d4', 0)
        """)
    op.execute("""
            INSERT INTO app_users (id, surname, family_name, email, password, blacklist) 
            VALUES (app_users_id_seq.NEXTVAL, 'Bob', 'User', 'bob@user.com', '$argon2id$v=19$m=65536,t=3,p=4$RNR/ZzUZ4S4a+DrTWzHoFw$QV6K0vFNr/f89mwdTxCCezLISmkYl+Y+7Z/yARL87d4', 0)
        """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('username', sa.VARCHAR(length=50), nullable=False))
    op.drop_index(op.f('ix_app_users_id'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.create_index(op.f('sys_c008667'), 'app_users', ['username'], unique=True)
    op.drop_column('app_users', 'blacklist')
    op.drop_column('app_users', 'email')
    op.drop_column('app_users', 'family_name')
    op.drop_column('app_users', 'surname')
    op.create_table('users',
    sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_c008655')),
    oracle_tablespace='USERS'
    )
    op.create_index(op.f('sys_c008656'), 'users', ['email'], unique=True)
    op.create_index(op.f('idx_users_name'), 'users', ['name'], unique=False)
    op.create_table('items',
    sa.Column('id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', oracle.NUMBER(precision=10, scale=2, asdecimal=True), nullable=False),
    sa.Column('is_offer', oracle.NUMBER(precision=1, scale=0, asdecimal=False), server_default=sa.text('0\r\n'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_c008663')),
    oracle_tablespace='USERS'
    )
    op.drop_index(op.f('ix_rent_books_id'), table_name='rent_books')
    op.drop_table('rent_books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
