"""initial_migration

Revision ID: c58af97cb89b
Revises: 
Create Date: 2026-09-17 14:06:07.863207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = 'c58af97cb89b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_users_name'), table_name='users')
    op.drop_index(op.f('sys_c008656'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('sys_c008667'), table_name='app_users')
    op.create_index(op.f('ix_app_users_id'), 'app_users', ['id'], unique=False)
    op.create_index(op.f('ix_app_users_username'), 'app_users', ['username'], unique=True)
    op.alter_column('items', 'price',
               existing_type=oracle.NUMBER(precision=10, scale=2, asdecimal=True),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.alter_column('items', 'price',
               existing_type=sa.Float(),
               type_=oracle.NUMBER(precision=10, scale=2, asdecimal=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_app_users_username'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_id'), table_name='app_users')
    op.create_index(op.f('sys_c008667'), 'app_users', ['username'], unique=True)
    op.create_table('users',
    sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=True, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_c008655')),
    oracle_tablespace='USERS'
    )
    op.create_index(op.f('sys_c008656'), 'users', ['email'], unique=True)
    op.create_index(op.f('idx_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###
